### ISSUE TITLE
What would my domain be ?, or how could I make this work from my cpanel

### ISSUE THREAD

**Issue by pedromaironi** [NDMAC/apk-updater#4]
What would my domain be ?, or how could I make this work from my cpanel

**Comment by gbourel** [comment]
You're domain could be anything you want. Basically you're current server's domain. But any subdomain may be used.
This server isn't currently used with cpanel but with a ssh connection.

**Comment by pedromaironi** [comment]
Port 443 in use by "Unable to open process" with PID 4!

**Comment by pedromaironi** [comment]
So I have to connect the server with ssh to cpanel

**Comment by gbourel** [comment]
This project is just a module for a Node application using the Express framework. It is intended to be used as a library in a main node application and isn't a standalone server.

**Comment by pedromaironi** [comment]
Well You dont have any implementation?, I'm trying implement that but, don't work.

**Comment by pedromaironi** [comment]
The documentation is very bad
